### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by OverSky-gtq** [18805699674/AiSpeak#1]
可以帮忙打包成apk吗，我家里人需要这个，但我不太懂

**Comment by 18805699674** [comment]
可以加我QQ 475539335 我发给你

**Comment by 18805699674** [comment]
https://www.pgyer.com/nc4S 可以在这里下载，不会用可以加我。小米可以直接添加的右下角-点击就可以切换打开和关闭了

**Comment by OverSky-gtq** [comment]
谢谢你
